name: scheduled workflow

on:
  schedule:
    - cron: "5 * * * *"
  push:
    branches:
      - master

env:
  SOMEONE: KBC

jobs:
  greet-someone:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout github repository
      uses: actions/checkout@v4
    
    - name: Greet someone
      id: greet
      uses: ./.github/actions/greet_someone
      with:
        who-to-greet: ${{ env.SOMEONE }}

    - name: Conditional check
      if: ${{ steps.greet.outputs.who-was-greeted != env.SOMEONE }}
      run: echo ${{ steps.greet.outputs.who-was-greeted }}
      shell: bash
