name: scheduled workflow

on:
  schedule:
    - cron: "5 * * * *"
  push:
    branches:
      - master

env:
  someone: KBC

jobs:
  greet-someone:
    runs-on: ubuntu-latest
    steps: 
    - name: Checkout github repository
      uses: actions/checkout@v4
    
    - name: Greet someone
      id: greet
      uses: ./.github/actions/greet_someone
      with:
        who-to-greet: $someone

    - name: Conditional check
      if: ${{ steps.greet.outputs.input == someone }}
      run: echo "Output matches input"
      shell: bash
