name: Protected envs and stages

on:
  push:
    branches:
      - master


jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environments: ["dev", "int", "prd"]
    environment: ${{ matrix.environments }}
    steps:
      - name: Checkout github repository
        uses: actions/checkout@v4

      - name: Build or simulate building
        run: sleep 5

      - name: Finish building
        run: echo "Build completed successfully"

#The 2nd job has to deploy to different environments defined by GitHub
#The job needs to fail for all the environments if one of the deployments fail
#The job has to only 1 deployment at a time (sequentially dev/int/prd)