name: Protected envs and stages

on:
  push:
    branches:
      - master


jobs:
  build-and-push:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github repository
        uses: actions/checkout@v4

      - name: Build or simulate building
        run: sleep 5

      - name: Finish building
        run: echo "Build completed successfully"

  # Chain the next job to the previous one and make it deploy
  # to different environments with manual approvals
  build-and-push-int:
    needs: build-and-push
    environment: int
    runs-on: ubuntu-latest
    steps:
      - name: Checkout github repository
        uses: actions/checkout@v4

      - name: Build or simulate building
        run: sleep 5

      - name: Finish building
        run: echo "Build completed successfully"

#The 2nd job has to deploy to different environments defined by GitHub
#The job needs to fail for all the environments if one of the deployments fail
#The job has to only 1 deployment at a time (sequentially dev/int/prd)